<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CONFI1_LIVEDASHHRCNonConfiSEA-BASED__8725ef</name>
   <tag></tag>
   <elementGuidId>dc71d3aa-04e5-461b-a1f2-8dbf2192a048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlProfiles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlProfiles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e685330c-32e9-4d13-ba4c-2f1f3bd3dfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlProfiles</value>
      <webElementGuid>8b155de1-7e14-4791-887c-b44e502c3b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ddlProfiles\',\'\')', 0)</value>
      <webElementGuid>60cb16d2-46ea-450e-a59f-8fc327d94465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlProfiles</value>
      <webElementGuid>5c41bd29-74c7-4f56-b53d-3c4ba5267304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0a0a098a-c6e9-417e-bf0c-88c9fc7cccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			CONFI1_LIVE
			DASHHRCNonConfi
			SEA-BASED_LIVE
			DAILY_LIVE
			WEEKLY_LIVE
			SEMI-MONTHLY_LIVE

		</value>
      <webElementGuid>950d628c-61dc-48fb-8121-6f819b98e567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlProfiles&quot;)</value>
      <webElementGuid>5499a380-9873-4aa0-8083-9c60da27dc1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlProfiles']</value>
      <webElementGuid>e07a7ff6-575b-4a37-8ba5-e56baabcead1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlLogin']/fieldset/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>06e984db-4a6b-418f-9fe7-693fa86e0e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::select[1]</value>
      <webElementGuid>354c3d2b-36ff-4377-a4b8-b54f6d48bae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter User ID'])[1]/following::select[1]</value>
      <webElementGuid>725f67c5-ad3c-4e11-9801-a959a0901185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Profile'])[1]/preceding::select[1]</value>
      <webElementGuid>64a5726f-922d-4cda-bc35-66f17757b035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>40cd3831-6f59-405a-aaf7-948bf0544be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a8806692-3e94-472e-98fa-38642b9e76cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlProfiles' and @id = 'ddlProfiles' and (text() = '
			CONFI1_LIVE
			DASHHRCNonConfi
			SEA-BASED_LIVE
			DAILY_LIVE
			WEEKLY_LIVE
			SEMI-MONTHLY_LIVE

		' or . = '
			CONFI1_LIVE
			DASHHRCNonConfi
			SEA-BASED_LIVE
			DAILY_LIVE
			WEEKLY_LIVE
			SEMI-MONTHLY_LIVE

		')]</value>
      <webElementGuid>69337aff-9de7-4dca-ac98-62b5ee73f4e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
