<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CONFI1_LIVEDASHHRCNonConfiPUFFI_WEEKLY_LIVE</name>
   <tag></tag>
   <elementGuidId>358eee1a-21cf-410b-9a46-30e0748a1278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlProfiles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlProfiles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d91a6cac-c6fa-4c96-9208-285d68e0be96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlProfiles</value>
      <webElementGuid>20a9001a-0681-45de-84f8-0a2891a68b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ddlProfiles\',\'\')', 0)</value>
      <webElementGuid>56f2f70c-8f0b-4c6a-9c9b-35c9932e8c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlProfiles</value>
      <webElementGuid>f4e50d3d-48df-4eb2-aae8-b6e6c148cf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d97bd2b-2eb2-4fe0-b4a6-df388a89e2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			CONFI1_LIVE
			DASHHRCNonConfi
			PUFFI_WEEKLY_LIVE

		</value>
      <webElementGuid>487751af-f514-4778-8f10-bea5e8452001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlProfiles&quot;)</value>
      <webElementGuid>eb22a115-40bd-497e-8fd7-a8d6b3848483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlProfiles']</value>
      <webElementGuid>8017f1fa-38dc-40cc-ba21-832c18c0c67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlLogin']/fieldset/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>54ecf6b6-2ab4-4712-8744-b18ac641f58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::select[1]</value>
      <webElementGuid>f003a1df-42a6-48a5-bc55-e8cd9683b910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter User ID'])[1]/following::select[1]</value>
      <webElementGuid>2df2cc0c-5e72-4ed2-9294-02fbd5fdb315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Profile'])[1]/preceding::select[1]</value>
      <webElementGuid>19944ae8-3829-4bff-8d90-5ee89d1363c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>2be4902e-dd16-4236-908c-9c92f3a42a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4491eb46-34dc-4fc6-b78f-ba671bf24466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlProfiles' and @id = 'ddlProfiles' and (text() = '
			CONFI1_LIVE
			DASHHRCNonConfi
			PUFFI_WEEKLY_LIVE

		' or . = '
			CONFI1_LIVE
			DASHHRCNonConfi
			PUFFI_WEEKLY_LIVE

		')]</value>
      <webElementGuid>d663892f-00ed-44ea-920a-06d732f2ecc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
