<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User ID_txtActiveDirectory</name>
   <tag></tag>
   <elementGuidId>2a323129-e982-401d-82fc-bd112e3919a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtActiveDirectory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtActiveDirectory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79ee3621-8c16-4c8d-b33b-57b473227651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtActiveDirectory</value>
      <webElementGuid>9800d5ac-3f44-4bf4-a8b8-9b29d854001b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4645095b-61be-4a9f-a114-47f284310d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a488fec1-8696-43d8-a52c-271bcb3b3bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript: processLogin();setTimeout('__doPostBack(\'txtActiveDirectory\',\'\')', 0)</value>
      <webElementGuid>4e438fa1-d00a-4411-84b1-c23e8d0fd404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>ce915ba1-0e72-4747-8e6b-23bd2805b121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtActiveDirectory</value>
      <webElementGuid>da01eb91-e34d-495c-83a7-3200eea4e234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtActiveDirectory&quot;)</value>
      <webElementGuid>a3990032-32f0-4d7a-b827-cbdc9f287815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtActiveDirectory']</value>
      <webElementGuid>5c705d46-2051-450e-be7d-0065289d1a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlLogin']/fieldset/table/tbody/tr/td[2]/input</value>
      <webElementGuid>3179f652-295d-4ed0-ac68-3f5b08a8545b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>63177dc7-e8df-43d8-9619-f67e385dd4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtActiveDirectory' and @type = 'text' and @id = 'txtActiveDirectory']</value>
      <webElementGuid>70ea7c6c-ed97-49f0-b694-fbddf39c4782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
