<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOME</name>
   <tag></tag>
   <elementGuidId>84ecc64d-2bbe-45ae-b7f9-90630d0efd9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ctl00_menuMain_1.ctl00_menuMain_3.ctl00_menuMain_14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_menuMainn0']/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>662c30c4-3dfd-4d58-8f11-758ace399975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctl00_menuMain_1 ctl00_menuMain_3 ctl00_menuMain_14</value>
      <webElementGuid>000d22cb-0b11-4ae9-92e4-9d6d940538a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../dashBoard.aspx</value>
      <webElementGuid>fefe68b5-f38b-4929-8dd7-05df51f31d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            HOME                                 
                                        </value>
      <webElementGuid>93cf732a-9f0b-4903-bb7f-c1633ecf7095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_menuMainn0&quot;)/table[@class=&quot;ctl00_menuMain_4 ctl00_menuMain_15&quot;]/tbody[1]/tr[1]/td[1]/a[@class=&quot;ctl00_menuMain_1 ctl00_menuMain_3 ctl00_menuMain_14&quot;]</value>
      <webElementGuid>26880649-d54d-4ca4-92b7-a109a6243446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_menuMainn0']/table/tbody/tr/td/a</value>
      <webElementGuid>198ddab2-7bce-4e58-b52e-b2aa120049ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOME')]</value>
      <webElementGuid>192a1a22-ac7e-4d73-85a2-b2ce683b47e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::a[3]</value>
      <webElementGuid>c6b96981-258a-46fc-a5ad-c06b39c8790a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSACTIONS'])[1]/preceding::a[1]</value>
      <webElementGuid>79a71343-17ed-4475-b4b9-60c6a18eaf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAINTENANCE'])[1]/preceding::a[2]</value>
      <webElementGuid>bd2aba7e-4747-48a4-bce8-3ba9d28bcc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../dashBoard.aspx')]</value>
      <webElementGuid>61c0643e-1118-4d7b-9702-60ad0e365a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>b093c504-b405-4ce8-b187-7f26cd954da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../dashBoard.aspx' and (text() = '
                                            HOME                                 
                                        ' or . = '
                                            HOME                                 
                                        ')]</value>
      <webElementGuid>20a680ef-08fe-435c-826a-416f5752f02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
